# Generated by Django 5.1.7 on 2025-03-25 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementoffer',
            name='accepted',
            field=models.ManyToManyField(blank=True, related_name='accepted_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlacementApproval',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('placed', models.BooleanField(default=False)),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_notification', to='main.notification')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_details', to='main.placementoffer')),
            ],
        ),
    ]
