# Generated by Django 5.1.7 on 2025-03-12 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reg_no',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('cgpa_required', models.DecimalField(decimal_places=2, max_digits=4)),
                ('no_of_backpapers', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('skillset', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('posted_date', models.DateField()),
                ('final_date', models.DateField()),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_placements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('appli_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.placement')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.student')),
            ],
            options={
                'unique_together': {('reg_no', 'offer_id')},
            },
        ),
        migrations.DeleteModel(
            name='PlacementOffer',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
