# Generated by Django 5.1.7 on 2025-03-31 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_placementoffer_accepted_placementapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementapproval',
            name='placed',
        ),
        migrations.AddField(
            model_name='placementapproval',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='placement_student_notification', to='main.student'),
        ),
    ]
